apiVersion: batch/v1
kind: CronJob
metadata:
  name: k8s-test
spec:
  schedule: "20 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: k6
            image: grafana/k6:latest
            args: ["run", "/scripts/test-case.js"]
            volumeMounts:
              - name: k6-scripts
                mountPath: /scripts
            env:
            - name: K6_OUT
              value: experimental-prometheus-rw
            - name: K6_PROMETHEUS_RW_SERVER_URL
              value: http://mimir-gateway.observability.svc.cluster.local/api/v1/push
            - name: K6_PROMETHEUS_RW_HEADERS
              value: X-Scope-OrgID=anonymous
          restartPolicy: OnFailure
          volumes:
            - name: k6-scripts
              configMap:
                name: k6-script